# Generated by Django 5.1.3 on 2026-08-30 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Commande créée'), ('order_confirmed', 'Commande confirmée'), ('order_processing', 'Commande en préparation'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('payment_received', 'Paiement reçu'), ('payment_failed', 'Paiement échoué'), ('invoice_created', 'Facture créée'), ('invoice_issued', 'Facture émise'), ('quote_sent', 'Devis envoyé'), ('quote_accepted', 'Devis accepté'), ('quote_declined', 'Devis refusé'), ('quote_expired', 'Devis expiré'), ('system', 'Système')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_model', models.CharField(blank=True, default='', max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
