# Generated by Django 5.1.3 on 2026-08-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_guest_address_order_guest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_shipping_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
